### ISSUE TITLE
Space before last character

### ISSUE THREAD

**Issue by tjvr** [tjvr/wiki-scratchblocks#1]
Some blocks appear obsolete when there is a space between the argument and the last character.

[example](http://wiki.scratch.mit.edu/wiki/Scratch_Wiki:Block_Plugin_Bugs#Spaces)

**Comment by tjvr** [comment]
@Choco31415 Do you know if this is still a problem?

**Comment by Choco31415** [comment]
I need to see an example to say for sure. The link you have does not seem to point to an example?

**Comment by tjvr** [comment]
Ah, it's in the archive: https://wiki.scratch.mit.edu/wiki/Scratch_Wiki:Block_Plugin_Bugs/Archive2#Spaces

**Comment by Choco31415** [comment]
I just checked with the latest version, and no, it's not an issue.

**Comment by tjvr** [comment]
Excellent. Thanks for checking!
