### ISSUE TITLE
Documentation on mediawiki.org

### ISSUE THREAD

**Issue by labster** [tjvr/wiki-scratchblocks#7]
https://www.mediawiki.org/wiki/Extension:ScratchBlocks is blank.  Can someone make a basic page there?  Even if it's just copying information from https://wiki.scratch.mit.edu/wiki/Block_Plugin?

Thanks!

**Comment by Choco31415** [comment]
There are currently two versions of the plugin. One that uses require_once and one that uses wfLoadExtension. Should we document both?

**Comment by labster** [comment]
Since I didn't know there were two versions of the extension... yes?  And why not just have one version, using the standard shim that reads the extension.json file?

You can document the install methods pretty easily with:
```
{{TNT|ExtensionInstall|ScratchBlocks|registration=1}}
```

**Comment by Choco31415** [comment]
I created the second version in response to your requests.

What do you mean by shim?

**Comment by labster** [comment]
I think I was thinking about the Localization shim, like here:
https://git.wikimedia.org/blob/mediawiki%2Fextensions%2FHeaderTabs/master/HeaderTabs.i18n.php

Note that this isn't exactly what I thought it was, either.  Sorry, I'm
relatively new to Mediawiki extension writing.  Just ignore the last
comment.

I think the goal would be to put both in the same repo.  Like there's no
reason why an extension.json file can't sit in the repo for a 1.19 wiki --
it would just ignore the file.  And it's not like setting
`$wgExtensionCredits` is harmful if it's already been loaded by
wfLoadExtension().

The other approach that's commonly used with Mediawiki extensions is to
make git branches that track new releases of the software.  So you have a
REL1_26 branch for the current software, and when 1.27 arrives, you make a
new branch that works on that called REL1_27.  And then you never backport
features to older branches.  (I never said this system was perfect).

**Comment by tjvr** [comment]
@Choco31415 @labster Is this solved?

**Comment by labster** [comment]
Because there is still no doc page at all on mediawiki.org, no.  This hasn't even been started.

I'd do it myself, but I honestly don't know anything about Scratch.  I assume it's some sort of computer language?  I'm just an ignorant Mediawiki farmer acting on the request of a user.

**Comment by tjvr** [comment]
@Choco31415 Want to do this? :)

**Comment by Choco31415** [comment]
I started a page, however I seem to be missing out on several things. @labster can you look?

**Comment by labster** [comment]
Updated https://www.mediawiki.org/wiki/Extension:ScratchBlocks.  The page could use a better description, but we're just about done here.

**Comment by tjvr** [comment]
Looks great! Thanks both :)
